# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import odservice_pb2 as odservice__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in odservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OdServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.stream_unary(
                '/odservice.OdService/UploadImage',
                request_serializer=odservice__pb2.ImageRequest.SerializeToString,
                response_deserializer=odservice__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.SendLogEntry = channel.unary_unary(
                '/odservice.OdService/SendLogEntry',
                request_serializer=odservice__pb2.LogEntry.SerializeToString,
                response_deserializer=odservice__pb2.LogResponse.FromString,
                _registered_method=True)


class OdServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadImage(self, request_iterator, context):
        """Upload the image file using client streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=odservice__pb2.ImageRequest.FromString,
                    response_serializer=odservice__pb2.ImageResponse.SerializeToString,
            ),
            'SendLogEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogEntry,
                    request_deserializer=odservice__pb2.LogEntry.FromString,
                    response_serializer=odservice__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'odservice.OdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('odservice.OdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OdService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/odservice.OdService/UploadImage',
            odservice__pb2.ImageRequest.SerializeToString,
            odservice__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/odservice.OdService/SendLogEntry',
            odservice__pb2.LogEntry.SerializeToString,
            odservice__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
