# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: odservice.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'odservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fodservice.proto\x12\todservice\"1\n\x0cImageRequest\x12\x12\n\nimage_file\x18\x01 \x01(\x0c\x12\r\n\x05model\x18\x02 \x01(\t\"\x99\x01\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cprocess_time\x18\x03 \x01(\x02\x12\x12\n\nthroughput\x18\x04 \x01(\x02\x12\r\n\x05power\x18\x05 \x01(\x02\x12\x14\n\x0c\x63pu_utilized\x18\x06 \x01(\x02\x12\x17\n\x0fmemory_utilized\x18\x07 \x01(\x02\"\xf7\x01\n\x08LogEntry\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x12\n\nip_address\x18\x04 \x01(\t\x12\x14\n\x0cprocess_time\x18\x05 \x01(\x02\x12\x1a\n\x12grpc_response_time\x18\x06 \x01(\x02\x12\x1b\n\x13total_response_time\x18\x07 \x01(\x02\x12\x12\n\nthroughput\x18\x08 \x01(\x02\x12\r\n\x05power\x18\t \x01(\x02\x12\x14\n\x0c\x63pu_utilized\x18\n \x01(\x02\x12\x17\n\x0fmemory_utilized\x18\x0b \x01(\x02\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x90\x01\n\tOdService\x12\x44\n\x0bUploadImage\x12\x17.odservice.ImageRequest\x1a\x18.odservice.ImageResponse\"\x00(\x01\x12=\n\x0cSendLogEntry\x12\x13.odservice.LogEntry\x1a\x16.odservice.LogResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=79
  _globals['_IMAGERESPONSE']._serialized_start=82
  _globals['_IMAGERESPONSE']._serialized_end=235
  _globals['_LOGENTRY']._serialized_start=238
  _globals['_LOGENTRY']._serialized_end=485
  _globals['_LOGRESPONSE']._serialized_start=487
  _globals['_LOGRESPONSE']._serialized_end=534
  _globals['_ODSERVICE']._serialized_start=537
  _globals['_ODSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
